name: build-cpu

on:
  push:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get -y install fftw3
    - run: sudo apt-get -y install libgsl-dev
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: ./setup
    - run: ls ${GITHUB_WORKSPACE}
    - run: ls 
    - env:
        PYTHONPATH: "${GITHUB_WORKSPACE}/lib/python"
    - run: echo $PYTHONPATH
